#+TITLE: Fediverse review
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='styles.css' />
#+OPTIONS: html-style:nil toc:nil num:nil 
#+TAGS: software

* What is the fediverse?
The fediverse is a lot of software such as [[https://en.wikipedia.org/wiki/Mastodon_(software)][Mastodon]], [[https://en.wikipedia.org/wiki/PeerTube][peertube]] and a lot more I will try and cover my experiences with different federation software I have used in this article. I find a new one of them everyday.

All of these federation programs have one thing in common, there are multiple servers that run the software independently from each other. Yet they still access one another as *one*. Let's say a peertube self hosted instance https://tube.tchncs.de is really cool with all of it's creators and content but finds out about a another peertube instance called https://diode.zone. Imediatly https://tube.tchncs.de maintainer can let the instance on the front page and other parts of the website show videos from https://diode.zone. Useres on https://tube.tchncs.de can like, dislike, comment, view and do everything they want even though https://diode.zone is a completely different server then https://tube.tchncs.de. *But* let's say https://diode.zone stops moderation and now porn is overflooding the instance. Uh oh you might think! The server maintainer of https://tube.tchncs.de may not like that so he decides to immediatly close connections to https://diode.zone and continue to connect to other instances he likes. Now this isn't even to say that a user on https://tube.tchncs.de can still visit https://diode.zone and watch videos and interact with there https://tube.tchncs.de account. Maybe your not a consumer but actually a content creator and are posting NSFW or highly mythical, not accepting of the [[https://en.wikipedia.org/wiki/Flying_Spaghetti_Monster][flying sphageti monster]] type of content. On peertube all you got to do is find a instance and read one that let's you post whatever the hell you want and now you get to enjoy content posting freedome.

As you can see this federation stuff is *awesome*. It has been adapted for all forms of social media of any kind. It's so powerfule. No user can hate the platform because they get banned and multiple server owners are in control not just *one* big corporation like google for YouTube. So hopefully you get my explination. [[https://en.wikipedia.org/wiki/PeerTube][PeerTube]] is not the only fediverse thing out there. There are multiple others and I would like to talk about all that I know of.

* Peertube
PeerTube as the name suggest's is similar in a way to something like YouTube. Just really nail's down on the *You* part. It's a video platform which can do anything that youtube can in a more minimal and privacy respecting way.

- Upload videos
- Upload livestreams
- Upload whatever you want (Have to find a instance, but *yes*)
- Like/dislike
- Comments
  
There are also a lot of cool content creators on it. A lot of them not really well known but still make super cool stuff. Not just about tech or GNU/Linux.

** Bad things:
From user experience I would say it looks really scarry, but don't be scared. I am pretty sure that if you can read this article you have enouph ability to use peertube ;)

I can not find a easy way to do publishing with it without actual software. However I believe they are not as much of a spyware like [[https://lbry.ix.tc][odysee.com]] is.

* Matrix
Is definitely a known in the category of FOSS chat clients as a great alternative to whatsapp, discord, skype and facebook/twiter messanger. Matrix is a federation software that handles many things:
- Joining rooms
- Reaction emoticons
- Replies
- Creating chat messages
- Groups/Spaces (Multiple chat rooms packaged together)
- Mentioning users
- Private chat
- *MULTIPLE CLIENTS*

So matrix has everything. Maybe, your in a touph situation where you need to use a properietary software for chatting. Most likely there is a way for you to mirror the messages from the proprietary chat thing to matrix. You would just need to talk to the chat room owner if you can put in a bot there for the mirror.

Another thing that matrix has is a *lot* of clients. You can deffinitly find a client that you like, suits your needs and is FOSS software. One thing to keep in mind that maybe you wouldn't think of if you used proprietary chat stuff before is that everything you send in a room is *public*. Anyone can grab out there screenshot tool or camera and take a snap at your message. However, this is not the case in private chats, since *encryption* and the person your chatting to you probably trust not to leak stuff you send. 
** Bad things
There are not a lot of none JS bloatware matrix clients. I geuss you don't need to care about how bloated a FOSS peice of software like matrix is. But I think it's nice to have a more minimal client. Minimal clients that I know of are:

- Quaternion
- Gomuks
- Matrixcli
- Neochat
- Mirage
- Nheko
- Ement (emacs)
Plenty to choose from but most all of them have there issues.
* Mastodon/Pleroma
Mastodon/Pleroma are a alternative to something like twitter or maybe in some cases reddit. They are both practically the same it's just Mastodon forces you to have a smaller character limit. I think this has the benefits of helping yourself make sure to be really concise with what your talking about. I think of Mastodon/Pleroma as a place to discuss certain topics in a organized way and also a place to notify people about what your doing in life. Mastodon/Pleroma is are two really great peaces of software that work really well together and by themselves and other instances or stuff on federation. There is truly no excuse for people to continue using twitter. (I can't think of one)

** Clients
You can obviously use whatever your instance that you chose uses in your web browser. But that's really not cool and bloated. I would rather have my own app on my machine that I control. I also don't want it to be bloated javascript.

The options from what I understand are not that many but okay. NOTE: I can not guarantee that all these work on pleroma. Most likely they do. If they don't and you use pleroma consider reporting a issue on there repo asking for support :)
- Toot (A python package for doing all things on mastodon.)
- Mastodon.el (A mastodon/pleroma package for emacs.)
- BloatFE (Runs in browser but is very lightweight.)
  
** My video "Use Mastodon/Pleroma!"
[[https://tube.tchncs.de/w/fXS18zwhRBzPo1VkmJRamg][Peertube]], [[https://lbry.ix.tc/@trueauracoral:a/Use-Mastodon:2][librarian]]
  
* Invidious
Invidious is a very plain topic. The software works well and *you* should use it!
** My video "Use Invidious!"
[[https://tube.tchncs.de/w/e9MmjxwqnR7RnFaYtVueWg][Peertube]], [[https://lbry.ix.tc/@trueauracoral:a/Use-Invidious%21:1][librarian]]
* Plume
Plume is a MD article posting place. It is supposed to work, I have a account there but it's not letting me post articles without shrinking them into one big line. Other people have it all working. It seems like plume is still in early development. One day I think it will be really good. For now it's usable but you may have issues with it.
* Fchan
Fchan is another software that's a bit early in development but it definitely works! It is a FOSS image board that looks a lot like 4chan. It works well it's just lacking in users. I asked 4chan why there still on proprietary 4chan, they said "All my friends are on it!" 4chan even decided to close the post! Absolutely horrible! Go use fchan (Fedderated channels).

