#+TITLE: How to degoogle
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='styles.css' />
#+OPTIONS: html-style:nil toc:nil num:nil
#+TAGS: software 

* Google's Popularity
Google is like a household name to a lot of people that use the computer. For the price of *0 DOLLARS* the registered account gets access to free email. Email is essential for authenticating accounts, messaging freinds and a lot of things. So you need a email and you just turn to google. 

I remember being super young and someone brought up having a email. Saying:
"You can't make a google account without being over 13!"

I thought this was strange and wanted to see if this was true. Going to my computer I tried and was locked from making a account, just because I was 8 years old and not 13. What I didn't know is all the information I just gave to google right the and there. I gave my real birth date, name, last name probably home address. *Everything*.

Now imagine this scenario with people actually use the google service.

* Google's services
With google you get a LOT of services. Each and every one of them is proprietary. Each and everyone of them gives your data to google. I want in this article to go over them and show some good alternatives.
** Gmail
This is a tough cookie to get away from. A lot of privacy/GNU/Linux enthusiasts even use gmail. Email is not secure. Go to [[https://anon.sx][searx]] and find out why. So you might be thinking why not use gmail? All your messages go to google's services as well as using proprietary software just to create a account. Even if you used proprietary software to create it a long time ago and are sitting nicely with a gmail drawer of emails in your email client. Your still having all your emails able to be read by google. That is not fun at all.

The solution this is using a alternative mail service. There are a couple at the time of posting this article that I think are good.

- *Tormail* is some sort of mail service managed in tor. I haven't used it myself
- *Disroot* is a public email service. All your emails could be read by disroot but at least disroot isn't google. So far there aren't any privacy claims against them.
- *matthewevan.xyz*. Matthew Evan or MattMadness actually gave me a email that works online and on the phone through a web app. It also should work through a email client. Possibly you can ask him and he will grant you with a awesome email

** Youtube
Youtube is terrible and I bet it will be a cause for the death of humanity. I covered out more reasons and how to switch from youtube to something else in this article: [[https://odysee.com/@trueauracoral:a/do-not-use-youtube:b][Do not use Youtube.]]

** G Suit
Google's g suit is a set of office tools. A obvious and really great alternative to this is [[https://[libreoffice]]. Libreoffice docx exports to g suite products from my experience in the past were good.
** Google's Search Engine
Google is named by its search engine. The alternatives to google's search engine are a LOT.

- *Searx*, I made a article on this already on how to set it up: [[https://zortazert.codeberg.page/Blog/searx.html][Search Engines (Searx)]]
- *SearxNG* is searx but more modern looking.
- *Whoogle* is basicly a google viewer
- *DuckDuckGo* I only advise using duckduckgo if your on your phone and have no other option.
** Google maps.
The best alternative to it is not *waze* that is literally also owned by google apparently. The best alternative is openstreetmaps. It for sure isn't a perfect solution. But at least you will find yourself using googlemaps/waze less.
** Chrome Browser
There is absolutely no reason to use chrome. https://spyware.neocities.org/articles/chrome.html This article does a great job explaining how bad it is. There are very few browsers left out there that are decent even.
- *Qutebrowser* is great with the only downside of it being that you need to know some basic vim keys to use it. However you should be able to just use your mouse for everything.
- *Otter-Browser* In development but looks awesome
- *Ice-cat* Best browser ever. Just you may need a regular browser for some things.
** Google Drive
Nextcloud does a lot of things but primarily its supposed to back up files and be a google alternative. https://github.com/nextcloud/providers Here they show all the public instances, but you can obviously host your own
** Google Playstore
Fdroid is a libre software focused app store for phones.

# * Troler Recommendations
# Android Auto
# Android OS
# - Ubuntu Touch
# 
# Android TV
# 
# Calendar
# - Simple Calendar
# 
# Cardboard
# 
# Chrome
# - Firefox
# 
# Chrome Enterprise
# 
# Chromebook
# - Thinkpad
# 
# Chromecast
# 
# Connected Home
# 
# Contacts
# - Simple Contacts
# 
# Digital Wellbeing
# - GNU care
# 
# Docs
# - LibreOffice
# 
# Drive
# - NextCloud
# 
# Earth
# 
# Exposure Notifications
# 
# Finance
# 
# Forms
# 
# Gboard
# 
# Gmail
# - Matthewevan.xyz
# 
# Google Alerts
# 
# Google Arts & Culture
# 
# Google Assistant
# 
# Google Authenticator
# 
# Google Chat
# 
# Google Classroom
# 
# Google Duo
# - Simple Dialer
# 
# Google Expeditions
# 
# Google Family Link
# 
# Google Fi
# 
# Google Files
# - NextCloud
# 
# Google Find My Device
# 
# Google Fit
# 
# Google Flights
# 
# Google Fonts
# - Simple Fonts
# 
# Google Groups
# 
# Google Home App
# 
# Google Input Tools
# 
# Google Lens
# 
# Google Meet
# 
# Google One
# - NextCloud
# 
# Google Pay
# 
# Google Photos
# - Simple Gallery
# 
# Google Play
# - F-Droid
# 
# Google Play Books
# 
# Google Play Games
# 
# Google Play Pass
# 
# Google Play Protect
# 
# Google Podcasts
# - AntennaPod
# 
# Google Shopping
# 
# Google Street View
# 
# Google TV
# 
# Google Tasks
# 
# Google Workspace
# 
# Hangouts
# 
# Keep
# 
# Maps
# - OpenStreet Maps
# 
# Messages
# 
# News
# 
# PhotoScan
# 
# Pixel
# 
# Pixel Buds
# 
# Pixelbook
# 
# Scholar
# 
# Search
# 
# Sheets
# 
# Sites
# 
# Slides
# 
# Snapseed

# Stadia
# 
# Tilt Brush
# 
# Translate
# 
# Travel
# 
# Voice
# 
# Waze
# 
# Wear OS by Google
# 
# YouTube
# - Invidious
# 
# YouTube Kids
# 
# YouTube Music
# 
# YouTube TV
# 
# YouTube VR                                                                                                                          
# * Ayyzee Recommendations
# Android OS
# - Ubuntu Touch
# - replicant
# 
# Android TV
# - Kodi
# - Jellyfin
# 
# Calendar
# - Simple Calendar
# 
# Cardboard
# - VRCadia
# 
# Chrome
# - Firefox
# 
# Chrome Enterprise
# 
# Chromebook
# - Thinkpad
# - FrameWork
# - Librem 15
# - System76
# 
# Chromecast
# - Raspberry Pi
# 
# Connected Home
# - Home Assistant (Open Source Not 100% libre)
# 
# Contacts
# - Simple Contacts
# 
# Digital Wellbeing
# - GNU care
# 
# Docs
# - LibreOffice
# 
# Drive
# - NextCloud
# - OWNCLOUD
# - SFTP
# 
# Earth
# - KDE Marble
# 
# Exposure Notifications
# 
# Finance
# 
# Forms
# - Nextcloud forms
# 
# Gboard
# - FlorisyBoard
# 
# Gmail
# - Matthewevan.xyz
# 
# Google Alerts
# - notify-send 🤣
# 
# Google Arts & Culture
# 
# Google Assistant
# - Home assistant
# 
# Google Authenticator
# - andOTP
# 
# Google Chat
# - Matrix
# 
# Google Classroom
# - Jitsi
# 
# Google Duo
# - Simple Dialer
# 
# Google Expeditions
# 
# Google Family Link
# 
# Google Fi
# 
# Google Files
# - NextCloud
# 
# Google Find My Device
# - Don't misplace or lose your device
# 
# Google Fit
# - Pen and paper diary
# 
# Google Flights
# 
# Google Fonts
# - Simple Fonts
# 
# Google Groups
# 
# Google Home App
# 
# Google Input Tools
# 
# Google Lens
# 
# Google Meet
# - Jitsi
# 
# Google One
# - NextCloud Hub
# 
# Google Pay
# 
# Google Photos
# - Simple Gallery
# 
# Google Play
# - F-Droid
# 
# Google Play Books
# 
# Google Play Games
# 
# Google Play Pass
# 
# Google Play Protect
# - AppArmor
# - SE-Linux
# 
# Google Podcasts
# - AntennaPod
# 
# Google Shopping
# 
# Google Street View
# 
# Google TV
# 
# Google Tasks
# 
# Google Workspace
# 
# Hangouts
# 
# Keep
# 
# Maps
# - OpenStreet Maps
# 
# Messages
# 
# News
# 
# PhotoScan
# 
# Pixel
# 
# Pixel Buds
# 
# Pixelbook
# 
# Scholar
# 
# Search
# 
# Sheets
# 
# Sites
# 
# Slides
# 
# Snapseed
# - GIMP
# - RAWTHERAPEE
# 
# Stadia
# - VNC 🤣
# 
# Tilt Brush
# 
# Translate
# 
# Travel
# 
# Voice
# 
# Waze
# 
# Wear OS by Google
# 
# YouTube
# - Invidious
# - Newpipe
# 
# YouTube Kids
# 
# YouTube Music
# 
# YouTube TV
# 
# YouTube VR