#+TITLE: Sleep Tutorial
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='styles.css' />
#+OPTIONS: html-style:nil toc:nil num:nil 
#+TAGS: tutorial

I have for the longest time since about early 2020 had issues of bringing my phone to my bed hindering my sleep. I in the later half of 2025. Conquered this however i still make this mistake sometimes. At least it's not as bad as it once was.

The biggest thing is that bringing your phone to your bed is a habit. It's a choice you make that you must fight. Like any habit you must be able to say *"NO"* to yourself, make that a habit.

* Choice: do not bring the phone to bed. FIGHT YOUR DEMONS
	- you must wrestle with your sleep and try to sleep.
	- KEEP PUSHING TILL  YOU REACH SLEEP. An effective strategy for me is to just keep on pondering and thinking till eventually without realizing it you just fall asleep
	- If only there was button that just magically made you go to sleep
		- However, using drugs is bad
	- It takes 3 days to get a normal sleep schedule I heard somewhere
* Tiredness
  - Being tired is the easiest method to go to sleep. It's so easy to take a nap when you're tired but that will take away the ability to sleep when it counts. Be physically tired and sleeping is easy.
- Sleep Schedule the more days which you have a good sleep the easier it gets
- Mental being mentally tired helps a lot.
- Physical tiredness is the method I used for a long time as a child to get to sleep. it is extremely effective
* The intracies of how I get to bed
1. Head, jaw, face, muscles and everything should be relaxed. My limbs must be straighted out.
2. I can only get to sleep by sleeping frontwards or on my back. However when I go to sleep on my back I usually wake up on my front somehow.
3. No body part should be on another because that retracts blood flow
4. I can only get sleep with my head tilted towards the left but most of the time I need a pillow to prop it up.
5. My full body must be completely coverd in a blanket. I can sleep without a blanket though sometimes
6. I must be tired in order to go to sleep
7. All thoughts must be pushed away in order to get into a good stage of sleep. Basically I must forget that I exist
8. Having all suroundings pitch black is good. Unplug all light sources.
9. No noise helps
